name=input("enter the name")
branch=input("enter the branch")
gender=input("enter the branch")
collegename=input("enter the college name")
age=int(input("enter the age"))
print("Name",name)
print("Branch",branch)
print("Gender",gender)
print("College name",collegename)
print("Age",age)
